### PR TITLE
Two small fixes

### LINKED ISSUE #1: Add the ability to support pluralized routes
Right now models, database table and route pluralization is inconsistent:

For example:

db table: products
model: Product
endpoint: /api/v1/product

I've had requests to allow the route to be pluralized. For example:

endpoint: `/api/v1/products` or `/api/v1/products/1`

This should be added as an option to the configuration file:

let api = require('bookshelf-api')({
    path: path.join(__dirname, 'models'),
    pluralEndpoints: true
});

A quick look shows that this might be helpful: https://github.com/blakeembrey/pluralize

### PR DESCRIPTION
**Pull request by rchavik**
Closes #1 and #5

### CODE REVIEW

**Comment by alarner** [comment]
@rchavik this is awesome! Thank you for submitting these fixes and new features. It would be great to add some unit tests for the new pluralized routes option in [this file](https://github.com/alarner/bookshelf-api/blob/master/test/index.js). If you don't have the time for it I'm happy to write them. Just let me know.

**Comment by rchavik** [comment]
@alarner can you help with the tests. i'm still learning testing in nodejs.

Thanks

**Comment by rchavik** [comment]
Thanks for merging.

Unfortunately, I missed the `hasTimestamp` fix in put.js.  Sorry. I'll try to submit a separate one next week.

**Comment by alarner** [comment]
@rchavik I caught that when I was writing tests. It should be good.

**Pull request merged**
